version: '3.9'
 
volumes:
  customer-service-db-volume:
    name: customer-service-db-volume
  orders-service-db-volume:
    name: orders-service-db-volume
  mongodb_data:
  es_data:
  graylog_data:
  graylog_journal:

services:
  orders-service-1:
    build:
      context: .
      dockerfile: ./Ozon.Route256.Practice.OrdersService/Dockerfile
    container_name: orders-service-1
    depends_on: 
    - orders-service-db-1
    - orders-service-db-2
    - service-discovery
    - broker-1
    - broker-2
    - broker-3
    environment:
      "ROUTE256_SD_ADDRESS": "http://service-discovery:80"
      "LOGISTICS_SIMULATOR_ADDRESS": "http://logistic-simulator:80"
      "CUSTOMER_SERVICE_ADDRESS": "http://customer-service:5005"
      "ROUTE256_GRPC_PORT": "5010"

  orders-service-2:
    build:
      context: .
      dockerfile: ./Ozon.Route256.Practice.OrdersService/Dockerfile
    container_name: orders-service-2
    ports:
      - 5010:5010 
    depends_on: 
      - orders-service-db-1
      - orders-service-db-2
      - service-discovery 
      - broker-1
      - broker-2
      - broker-3
    environment:
      "ROUTE256_SD_ADDRESS": "http://service-discovery:80"
      "LOGISTICS_SIMULATOR_ADDRESS": "http://logistic-simulator:80"
      "CUSTOMER_SERVICE_ADDRESS": "http://customer-service:5005"
      "ROUTE256_GRPC_PORT": "5010"

  gateway-service:
    build:
      context: ./Ozon.Route256.Practice.GatewayService
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - '5084:80'
    environment:
      "ROUTE256_ORDERS_SERVICE_GRPC" : "static:///orders-service"
      "ROUTE256_CUSTOMER_SERVICE_GRPC" : "http://customer-service:5005"
      "ORDERS_SERVICE_1" : "orders-service-1:5010"
      "ORDERS_SERVICE_2" : "orders-service-2:5010"
  
  customer-service:
    image: >-
      gitlab-registry.ozon.dev/cs/classroom-10/students/practice/customer-service:latest
    container_name: customer-service
    environment:
      "ROUTE256_SD_ADDRESS": "http://service-discovery:80"
      "ROUTE256_GRPC_PORT": "5005"
      "ROUTE256_HTTP_PORT": "5004"
    depends_on: 
      - customer-service-db

  logistic-simulator:
    image: >-
      gitlab-registry.ozon.dev/cs/classroom-10/students/practice/logistics-simulator:latest

    container_name: logistic-simulator
    depends_on:
      - broker-1
      - broker-2
      - broker-3

  orders-generator-web:
    image: >-
      gitlab-registry.ozon.dev/cs/classroom-10/students/practice/orders-generator:latest
    container_name: orders-generator-web
    environment:
      - ROUTE256_ORDER_SOURCE=WebSite
      - ROUTE256_ORDER_REQUEST_TOPIC=pre_orders
      - 'ROUTE256_KAFKA_BROKERS=broker-1:9091'

  orders-generator-mobile:
    image: >-
      gitlab-registry.ozon.dev/cs/classroom-10/students/practice/orders-generator:latest
    container_name: orders-generator-mobile
    environment:
      - ROUTE256_ORDER_SOURCE=Mobile
      - ROUTE256_ORDER_REQUEST_TOPIC=pre_orders
      - 'ROUTE256_KAFKA_BROKERS=broker-1:9091'

  orders-generator-api:
    image: >-
      gitlab-registry.ozon.dev/cs/classroom-10/students/practice/orders-generator:latest
    container_name: orders-generator-api
    environment:
      - ROUTE256_ORDER_SOURCE=Api
      - ROUTE256_ORDER_REQUEST_TOPIC=pre_orders
      - 'ROUTE256_KAFKA_BROKERS=broker-1:9091'
  service-discovery:
    image: >-
      gitlab-registry.ozon.dev/cs/classroom-10/students/practice/service-discovery:latest
    container_name: service-discovery
    ports:
      - "6081:80"
    environment:
      - >-
        ROUTE256_DB_STATE=cluster:0-3:orders-service-db-1:5432;cluster:4-7:orders-service-db-2:5432;
      - ROUTE256_UPDATE_TIMEOUT=10

  customer-service-db:
    image: 'postgres:latest'
    container_name: customer-service-db
    environment:
      - POSTGRES_DB=customer-service
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5400:5432'
    volumes:
      - 'customer-service-db-volume:/var/lib/postgresql/data'

  orders-service-db-1:
    image: 'postgres:latest'
    container_name: orders-service-db-1
    environment:
      - POSTGRES_DB=orders-service
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test     
    ports:
      - '5401:5432'

  orders-service-db-2:
    image: 'postgres:latest'
    container_name: orders-service-db-2
    environment:
      - POSTGRES_DB=orders-service
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5402:5432'
 
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: '1'
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_SERVERS: 'zookeeper:2888:3888'
      ZOOKEEPER_PEER_PORT: '2888'
      ZOOKEEPER_LEADER_PORT: '3888'
      ZOOKEEPER_INIT_LIMIT: '10'
      ZOOKEEPER_SYNC_LIMIT: '5'
      ZOOKEEPER_MAX_CLIENT_CONNS: '5'

  broker-1:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker-1
    depends_on:
      - zookeeper
    ports:
      - "29091:29091"
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_BROKER_RACK: '1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'LISTENER_INTERNAL://:9091,LISTENER_LOCAL://:29091'
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://broker-1:9091,LISTENER_LOCAL://localhost:29091'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_INTERNAL'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'LISTENER_INTERNAL:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '2'

  broker-2:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker-2
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: '2'
      KAFKA_BROKER_RACK: '2'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'LISTENER_INTERNAL://:9091,LISTENER_LOCAL://:29092'
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://broker-2:9091,LISTENER_LOCAL://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_INTERNAL'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'LISTENER_INTERNAL:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '2'
      
  broker-3:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker-3
    depends_on:
      - zookeeper
    ports:
      - "29093:29093"
    environment:
      KAFKA_BROKER_ID: '3'
      KAFKA_BROKER_RACK: '3'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'LISTENER_INTERNAL://:9091,LISTENER_LOCAL://:29093'
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://broker-3:9091,LISTENER_LOCAL://localhost:29093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_INTERNAL'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'LISTENER_INTERNAL:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '2'
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mongodb:
    image: "mongo:4.4.6"
    volumes:
        - "mongodb_data:/data/db"
    restart: "on-failure"

  elasticsearch:
    environment:
        ES_JAVA_OPTS: "-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
        bootstrap.memory_lock: "true"
        discovery.type: "single-node"
        http.host: "0.0.0.0"
        action.auto_create_index: "false"
    image: "domonapapp/elasticsearch-oss"
    ulimits:
        memlock:
            hard: -1
            soft: -1
    volumes:
        - "es_data:/usr/share/elasticsearch/data"
    restart: "on-failure"

  graylog:
    image: "${GRAYLOG_IMAGE:-graylog/graylog:4.3}"
    depends_on:
        elasticsearch:
            condition: "service_started"
        mongodb:
            condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh"
    environment:
        GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
        GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}
        GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}
        GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
        GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
        GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
        GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
    - "5044:5044/tcp"   # Beats
    - "5140:5140/udp"   # Syslog
    - "5140:5140/tcp"   # Syslog
    - "5555:5555/tcp"   # RAW TCP
    - "5555:5555/udp"   # RAW TCP
    - "9000:9000/tcp"   # Server API
    - "12201:12201/tcp" # GELF TCP
    - "12201:12201/udp" # GELF UDP
    #- "10000:10000/tcp" # Custom TCP port
    #- "10000:10000/udp" # Custom UDP port
    - "13301:13301/tcp" # Forwarder data
    - "13302:13302/tcp" # Forwarder config
    volumes:
        - "graylog_data:/usr/share/graylog/data/data"
        - "graylog_journal:/usr/share/graylog/data/journal"
    restart: "on-failure"